package com.example.exportfigma;


import android.app.Activity;
import android.os.Bundle;


import android.view.View;
import android.widget.TextView;
import android.widget.ImageView;

public class to_do_list_app_activity extends Activity {

	
	private View _bg__to_do_list_app_ek2;
	private View _bg__home_screen_ek1;
	private View _bg__greetings_session_ek1;
	private TextView good_evening__ivy;
	private View _bg__date_session_ek1;
	private View _bg__group_22_ek1;
	private View _bg__group_1_ek1;
	private View ellipse_1;
	private TextView _5;
	private TextView thur;
	private View _bg__group_23_ek1;
	private View _bg__group_2_ek1;
	private View ellipse_2;
	private TextView _6;
	private TextView fri;
	private View _bg__group_24_ek1;
	private View _bg__group_3_ek1;
	private View ellipse_3;
	private TextView _7;
	private TextView sat;
	private View _bg__group_25_ek1;
	private View _bg__group_4_ek1;
	private View ellipse_4;
	private TextView _8;
	private TextView sun;
	private View _bg__group_26_ek1;
	private View _bg__group_5_ek1;
	private View ellipse_5;
	private TextView _9;
	private TextView mon;
	private View _bg__group_27_ek1;
	private View _bg__group_6_ek1;
	private View ellipse_6;
	private TextView _10;
	private TextView tues;
	private View _bg__group_28_ek1;
	private View _bg__group_7_ek1;
	private View ellipse_7;
	private TextView _11;
	private TextView wed;
	private TextView today_s_tasks;
	private View ellipse_9;
	private View _bg__group_31_ek1;
	private View rectangle_13;
	private TextView search;
	private ImageView vector;
	private View _bg__frame_1_ek1;
	private View _bg__group_39_ek1;
	private View _bg__group_29_ek1;
	private TextView go_to_church;
	private TextView _8_00_am;
	private View _bg__group_38_ek1;
	private ImageView vector_ek1;
	private ImageView vector_ek2;
	private View rectangle_1;
	private View _bg__group_8_ek1;
	private View rectangle_6;
	private ImageView vector_ek3;
	private View _bg__group_12_ek1;
	private TextView wash_my_clothes;
	private View _bg__group_37_ek1;
	private ImageView vector_ek4;
	private ImageView vector_ek5;
	private TextView _2_00_pm;
	private View rectangle_1_ek1;
	private View _bg__group_8_ek3;
	private View rectangle_6_ek1;
	private ImageView vector_ek6;
	private View _bg__group_13_ek1;
	private TextView cook_for_the_family;
	private View _bg__group_36_ek1;
	private ImageView vector_ek7;
	private ImageView vector_ek8;
	private View rectangle_1_ek2;
	private TextView _12_00_pm;
	private View _bg__group_8_ek5;
	private View rectangle_6_ek2;
	private ImageView vector_ek9;
	private View _bg__group_16_ek1;
	private TextView make_my_hair;
	private View _bg__group_34_ek1;
	private ImageView vector_ek10;
	private ImageView vector_ek11;
	private TextView _6_00_pm;
	private View rectangle_1_ek3;
	private View _bg__group_8_ek7;
	private View rectangle_6_ek3;
	private ImageView vector_ek12;
	private View _bg__group_14_ek1;
	private TextView visit_chastity;
	private View _bg__group_35_ek1;
	private ImageView vector_ek13;
	private ImageView vector_ek14;
	private View rectangle_1_ek4;
	private View rectangle_4;
	private TextView _5_00_pm;
	private View _bg__group_32_ek1;
	private TextView work_on_an_assignment;
	private View rectangle_1_ek5;
	private View _bg__group_8_ek9;
	private View rectangle_6_ek4;
	private ImageView vector_ek15;
	private ImageView vector_ek16;
	private ImageView vector_ek17;
	private TextView _8_30_pm;
	private View _bg__group_33_ek1;
	private TextView call_my_brother;
	private View rectangle_1_ek6;
	private View rectangle_4_ek1;
	private ImageView vector_ek18;
	private ImageView vector_ek19;
	private TextView _8_00_pm;
	private View _bg__group_21_ek1;
	private View _bg__group_20_ek1;
	private ImageView rectangle_12;
	private View _bg__group_18_ek1;
	private View ellipse_8;
	private ImageView vector_ek20;
	private View _bg__group_19_ek1;
	private View _bg__group_17_ek1;
	private View rectangle_7;
	private View rectangle_8;
	private View rectangle_9;
	private View rectangle_10;
	private ImageView vector_ek21;
	private ImageView vector_ek22;
	private ImageView vector_ek23;

	@Override
	public void onCreate(Bundle savedInstanceState) {

		super.onCreate(savedInstanceState);
		setContentView(R.layout.to_do_list_app);

		
		_bg__to_do_list_app_ek2 = (View) findViewById(R.id._bg__to_do_list_app_ek2);
		_bg__home_screen_ek1 = (View) findViewById(R.id._bg__home_screen_ek1);
		_bg__greetings_session_ek1 = (View) findViewById(R.id._bg__greetings_session_ek1);
		good_evening__ivy = (TextView) findViewById(R.id.good_evening__ivy);
		_bg__date_session_ek1 = (View) findViewById(R.id._bg__date_session_ek1);
		_bg__group_22_ek1 = (View) findViewById(R.id._bg__group_22_ek1);
		_bg__group_1_ek1 = (View) findViewById(R.id._bg__group_1_ek1);
		ellipse_1 = (View) findViewById(R.id.ellipse_1);
		_5 = (TextView) findViewById(R.id._5);
		thur = (TextView) findViewById(R.id.thur);
		_bg__group_23_ek1 = (View) findViewById(R.id._bg__group_23_ek1);
		_bg__group_2_ek1 = (View) findViewById(R.id._bg__group_2_ek1);
		ellipse_2 = (View) findViewById(R.id.ellipse_2);
		_6 = (TextView) findViewById(R.id._6);
		fri = (TextView) findViewById(R.id.fri);
		_bg__group_24_ek1 = (View) findViewById(R.id._bg__group_24_ek1);
		_bg__group_3_ek1 = (View) findViewById(R.id._bg__group_3_ek1);
		ellipse_3 = (View) findViewById(R.id.ellipse_3);
		_7 = (TextView) findViewById(R.id._7);
		sat = (TextView) findViewById(R.id.sat);
		_bg__group_25_ek1 = (View) findViewById(R.id._bg__group_25_ek1);
		_bg__group_4_ek1 = (View) findViewById(R.id._bg__group_4_ek1);
		ellipse_4 = (View) findViewById(R.id.ellipse_4);
		_8 = (TextView) findViewById(R.id._8);
		sun = (TextView) findViewById(R.id.sun);
		_bg__group_26_ek1 = (View) findViewById(R.id._bg__group_26_ek1);
		_bg__group_5_ek1 = (View) findViewById(R.id._bg__group_5_ek1);
		ellipse_5 = (View) findViewById(R.id.ellipse_5);
		_9 = (TextView) findViewById(R.id._9);
		mon = (TextView) findViewById(R.id.mon);
		_bg__group_27_ek1 = (View) findViewById(R.id._bg__group_27_ek1);
		_bg__group_6_ek1 = (View) findViewById(R.id._bg__group_6_ek1);
		ellipse_6 = (View) findViewById(R.id.ellipse_6);
		_10 = (TextView) findViewById(R.id._10);
		tues = (TextView) findViewById(R.id.tues);
		_bg__group_28_ek1 = (View) findViewById(R.id._bg__group_28_ek1);
		_bg__group_7_ek1 = (View) findViewById(R.id._bg__group_7_ek1);
		ellipse_7 = (View) findViewById(R.id.ellipse_7);
		_11 = (TextView) findViewById(R.id._11);
		wed = (TextView) findViewById(R.id.wed);
		today_s_tasks = (TextView) findViewById(R.id.today_s_tasks);
		ellipse_9 = (View) findViewById(R.id.ellipse_9);
		_bg__group_31_ek1 = (View) findViewById(R.id._bg__group_31_ek1);
		rectangle_13 = (View) findViewById(R.id.rectangle_13);
		search = (TextView) findViewById(R.id.search);
		vector = (ImageView) findViewById(R.id.vector);
		_bg__frame_1_ek1 = (View) findViewById(R.id._bg__frame_1_ek1);
		_bg__group_39_ek1 = (View) findViewById(R.id._bg__group_39_ek1);
		_bg__group_29_ek1 = (View) findViewById(R.id._bg__group_29_ek1);
		go_to_church = (TextView) findViewById(R.id.go_to_church);
		_8_00_am = (TextView) findViewById(R.id._8_00_am);
		_bg__group_38_ek1 = (View) findViewById(R.id._bg__group_38_ek1);
		vector_ek1 = (ImageView) findViewById(R.id.vector_ek1);
		vector_ek2 = (ImageView) findViewById(R.id.vector_ek2);
		rectangle_1 = (View) findViewById(R.id.rectangle_1);
		_bg__group_8_ek1 = (View) findViewById(R.id._bg__group_8_ek1);
		rectangle_6 = (View) findViewById(R.id.rectangle_6);
		vector_ek3 = (ImageView) findViewById(R.id.vector_ek3);
		_bg__group_12_ek1 = (View) findViewById(R.id._bg__group_12_ek1);
		wash_my_clothes = (TextView) findViewById(R.id.wash_my_clothes);
		_bg__group_37_ek1 = (View) findViewById(R.id._bg__group_37_ek1);
		vector_ek4 = (ImageView) findViewById(R.id.vector_ek4);
		vector_ek5 = (ImageView) findViewById(R.id.vector_ek5);
		_2_00_pm = (TextView) findViewById(R.id._2_00_pm);
		rectangle_1_ek1 = (View) findViewById(R.id.rectangle_1_ek1);
		_bg__group_8_ek3 = (View) findViewById(R.id._bg__group_8_ek3);
		rectangle_6_ek1 = (View) findViewById(R.id.rectangle_6_ek1);
		vector_ek6 = (ImageView) findViewById(R.id.vector_ek6);
		_bg__group_13_ek1 = (View) findViewById(R.id._bg__group_13_ek1);
		cook_for_the_family = (TextView) findViewById(R.id.cook_for_the_family);
		_bg__group_36_ek1 = (View) findViewById(R.id._bg__group_36_ek1);
		vector_ek7 = (ImageView) findViewById(R.id.vector_ek7);
		vector_ek8 = (ImageView) findViewById(R.id.vector_ek8);
		rectangle_1_ek2 = (View) findViewById(R.id.rectangle_1_ek2);
		_12_00_pm = (TextView) findViewById(R.id._12_00_pm);
		_bg__group_8_ek5 = (View) findViewById(R.id._bg__group_8_ek5);
		rectangle_6_ek2 = (View) findViewById(R.id.rectangle_6_ek2);
		vector_ek9 = (ImageView) findViewById(R.id.vector_ek9);
		_bg__group_16_ek1 = (View) findViewById(R.id._bg__group_16_ek1);
		make_my_hair = (TextView) findViewById(R.id.make_my_hair);
		_bg__group_34_ek1 = (View) findViewById(R.id._bg__group_34_ek1);
		vector_ek10 = (ImageView) findViewById(R.id.vector_ek10);
		vector_ek11 = (ImageView) findViewById(R.id.vector_ek11);
		_6_00_pm = (TextView) findViewById(R.id._6_00_pm);
		rectangle_1_ek3 = (View) findViewById(R.id.rectangle_1_ek3);
		_bg__group_8_ek7 = (View) findViewById(R.id._bg__group_8_ek7);
		rectangle_6_ek3 = (View) findViewById(R.id.rectangle_6_ek3);
		vector_ek12 = (ImageView) findViewById(R.id.vector_ek12);
		_bg__group_14_ek1 = (View) findViewById(R.id._bg__group_14_ek1);
		visit_chastity = (TextView) findViewById(R.id.visit_chastity);
		_bg__group_35_ek1 = (View) findViewById(R.id._bg__group_35_ek1);
		vector_ek13 = (ImageView) findViewById(R.id.vector_ek13);
		vector_ek14 = (ImageView) findViewById(R.id.vector_ek14);
		rectangle_1_ek4 = (View) findViewById(R.id.rectangle_1_ek4);
		rectangle_4 = (View) findViewById(R.id.rectangle_4);
		_5_00_pm = (TextView) findViewById(R.id._5_00_pm);
		_bg__group_32_ek1 = (View) findViewById(R.id._bg__group_32_ek1);
		work_on_an_assignment = (TextView) findViewById(R.id.work_on_an_assignment);
		rectangle_1_ek5 = (View) findViewById(R.id.rectangle_1_ek5);
		_bg__group_8_ek9 = (View) findViewById(R.id._bg__group_8_ek9);
		rectangle_6_ek4 = (View) findViewById(R.id.rectangle_6_ek4);
		vector_ek15 = (ImageView) findViewById(R.id.vector_ek15);
		vector_ek16 = (ImageView) findViewById(R.id.vector_ek16);
		vector_ek17 = (ImageView) findViewById(R.id.vector_ek17);
		_8_30_pm = (TextView) findViewById(R.id._8_30_pm);
		_bg__group_33_ek1 = (View) findViewById(R.id._bg__group_33_ek1);
		call_my_brother = (TextView) findViewById(R.id.call_my_brother);
		rectangle_1_ek6 = (View) findViewById(R.id.rectangle_1_ek6);
		rectangle_4_ek1 = (View) findViewById(R.id.rectangle_4_ek1);
		vector_ek18 = (ImageView) findViewById(R.id.vector_ek18);
		vector_ek19 = (ImageView) findViewById(R.id.vector_ek19);
		_8_00_pm = (TextView) findViewById(R.id._8_00_pm);
		_bg__group_21_ek1 = (View) findViewById(R.id._bg__group_21_ek1);
		_bg__group_20_ek1 = (View) findViewById(R.id._bg__group_20_ek1);
		rectangle_12 = (ImageView) findViewById(R.id.rectangle_12);
		_bg__group_18_ek1 = (View) findViewById(R.id._bg__group_18_ek1);
		ellipse_8 = (View) findViewById(R.id.ellipse_8);
		vector_ek20 = (ImageView) findViewById(R.id.vector_ek20);
		_bg__group_19_ek1 = (View) findViewById(R.id._bg__group_19_ek1);
		_bg__group_17_ek1 = (View) findViewById(R.id._bg__group_17_ek1);
		rectangle_7 = (View) findViewById(R.id.rectangle_7);
		rectangle_8 = (View) findViewById(R.id.rectangle_8);
		rectangle_9 = (View) findViewById(R.id.rectangle_9);
		rectangle_10 = (View) findViewById(R.id.rectangle_10);
		vector_ek21 = (ImageView) findViewById(R.id.vector_ek21);
		vector_ek22 = (ImageView) findViewById(R.id.vector_ek22);
		vector_ek23 = (ImageView) findViewById(R.id.vector_ek23);
	
		
		//custom code goes here
	
	}
}
	
	